"""empty message

Revision ID: 950e616d4b13
Revises: b8db1bb9b1ae
Create Date: 2022-06-02 11:02:51.355083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950e616d4b13'
down_revision = 'b8db1bb9b1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint('book_ibfk_1', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'genre', ['genre_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_ibfk_1', 'book', 'author', ['author_id'], ['id'])
    op.drop_column('book', 'genre_id')
    # ### end Alembic commands ###
